server:
  port: 83

spring:
  application:
    name: cloudalibaba-nacos-consumer-order
  cloud:
    nacos:
      discovery:
        #server-addr: 127.0.0.1:8848 #测试本地nacos
        server-addr: 192.168.0.105:8840 #测试联想电脑上的nacos集群
