server:
  port: 80

eureka:
  client:
    #是否注册到eureka
    register-with-eureka: true
    # 是否在本地缓存注册表信息
    fetch-registry: true
    service-url:
      # 配置eureka的地址，如果多台则逗号分隔。
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  client:
    config:
      CLOUD-PROVIDER-PAYMENT-HYSTRIX:  #服务名，这里服务名需要大写
        #连接超时时间
        connectTimeout: 2000
        #读取超时时间
        readTimeout: 6000
        #配置默认的重试机制，可以不配置
        #retryer: feign.Retryer.Default
  hystrix:
      enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。
