server:
  port: 80

eureka:
  client:
    #是否注册到eureka
    register-with-eureka: true
    # 是否在本地缓存注册表信息
    fetch-registry: true
    service-url:
      # 配置eureka的地址，如果多台则逗号分隔。
      defaultZone: http://eureka7001.com:7001/eureka

ribbon:
  #调用接口读取超时时间
  ReadTimeout:  6000
  #调用接口连接超时时间
  ConnectTimeout: 2000

#开启Hystrix降级处理
feign:
  hystrix:
      enabled: true #在Feign中开启Hystrix。如果处理自身的容错就开启。开启方式与生产端不一样。

#设置超时熔断时间（spring-cloud-starter-openfeign中的HystrixCommandProperties默认为1000毫秒）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

#设置hystrix日志级别是DEBUG
logging:
  level:
   com.netflix.hystrix: DEBUG
